
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import AboutMe from '@/components/AboutMe'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'


export default function Home() {
 return (
  <div >
    <Head>
      <title>Kristians the developer</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" hef="/favicon.ico" />
    </Head>
    <div>
      <div className="navbar fixed top-0 left-0 right-0 z-50">
      <Navbar></Navbar>
      </div>
      <div>
        <div className='p-4 flex items-center justify-center mt-20'><AboutMe></AboutMe></div>
      </div>
      <div>
        <div className='p-4 flex items-center justify-center mt-20'><Projects></Projects></div>
      </div>
      <div>
        <div className='p-4 flex items-center justify-center mt-20'><Skills></Skills></div>
      </div>
      
    
    </div>

  
  </div>
 )
}
