
import Background from '@/components/Background'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import AboutMe from '@/components/AboutMe'
import Image from 'next/image'




export default function Home() {
 return (
  <div>
    <Head>
      <title>Kristians the developer</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" hef="/favicon.ico" />
    </Head>
    <Navbar></Navbar>
    <AboutMe></AboutMe>
    <Background></Background>
    
  
  </div>
 )
}
