
import Background from '@/components/Background'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import AboutMe from '@/components/AboutMe'





export default function Home() {
 return (
  <div>
    <Head>
      <title>Kristians the developer</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" hef="/favicon.ico" />
    </Head>
    <Background></Background>
    <Navbar></Navbar>
    <div className='p-10 '>
      <div>
        <div className='p-4 flex items-center justify-center'><AboutMe></AboutMe></div>
      </div>
    </div>
    
    
    
    
  
  </div>
 )
}
